name: Schedule Node.js Script

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
jobs:
  run-node-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # You can specify your Node.js version here

      - name: Install dependencies
        run: npm install
      - name: Check Node.js LTS Version
        run: |
          latest_lts_version=$(node src/getLatestNodeVersion.js)
          echo "Latest LTS version: $latest_lts_version"
          response=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases/tags/$latest_lts_version)
          existing_release=$(echo $response | jq -r '.message // "not found"')
          if [ "$existing_release" = "Not Found" ]; then
            echo "New Node.js LTS version detected: $latest_lts_version"
            echo "new_version=$latest_lts_version" >> $GITHUB_ENV
          else
            echo "No new Node.js LTS version found."
            echo "new_version=" >> $GITHUB_ENV
          fi
      - name: Run script
        if: env.new_version != ''
        run: node src/download.js

      - name: Create Draft Release
        if: env.new_version != ''
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.new_version }}
          release_name: Node.js ${{ env.new_version }} LTS Release
          draft: true
          prerelease: false
      - name: Find Asset Files
        if: env.new_version != ''
        id: find_assets
        run: |
          asset_files=$(find src/assets -type f)
          asset_files="${asset_files//'%'/'%25'}"
          asset_files="${asset_files//$'\n'/'%0A'}"
          asset_files="${asset_files//$'\r'/'%0D'}"
          echo "asset_files=$asset_files" >> $GITHUB_ENV

      - name: Upload Release Assets
        if: env.new_version != ''
        run: |
          asset_files="${{ env.asset_files }}"
          asset_files="${asset_files//'%0A'/$'\n'}"
          readarray -t asset_files <<< "$asset_files"
          for asset_file in "${asset_files[@]}"; do
            asset_name=$(basename "$asset_file")
            echo "Uploading asset: $asset_file"
            gh release upload ${{ env.new_version }} "$asset_file" --clobber -R ${{ github.repository }}
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Release
        if: env.new_version != ''
        run: |
          release_id="${{ steps.create_release.outputs.id }}"
          curl \
            -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"draft": false}' \
            "https://api.github.com/repos/${{ github.repository }}/releases/$release_id"
